
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DIoLMotor__H__
#define __DIoLMotor__H__

#include <Base_DIoLMotor.h>
#include <vector>
#include <string>
using vector = std::vector;
using string = std::string;

namespace Device
{

class
    DIoLMotor
    : public Base_DIoLMotor
{

public:
    /* sample constructor */
    explicit DIoLMotor (
        const Configuration::IoLMotor& config,
        Parent_DIoLMotor* parent
    ) ;
    /* sample dtr */
    ~DIoLMotor ();

    /* delegators for
    cachevariables and sourcevariables */
    /* Note: never directly call this function. */
    UaStatus writePositionSetPoint ( const std::vector<OpcUa_Double>& v);


    /* delegators for methods */
    UaStatus callStart_move (
        UaString& response
    ) ;

private:
    /* Delete copy constructor and assignment operator */
    DIoLMotor( const DIoLMotor& other );
    DIoLMotor& operator=(const DIoLMotor& other);

    static size_t curl_write_function(void* ptr, size_t size, size_t nmemb, std::string* data);
    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:
    void update();

    bool is_ready();

    UaStatus get_motor_info();
    UaStatus move_motor();

private:
    double m_position;
    double m_position_setpoint;
    bool m_is_ready; // declares where it is ready for operation
        // this essentially means that all settings are in a reasonable state
    bool is_moving_; // -- this variable will be set by a GPIO bit. That code is not ready yet
    double m_acceleration;
    double m_speed;
    double m_torque;
    double m_temperature;
    string m_address;

};

}

#endif // __DIoLMotor__H__
