# This file has been generated by quasar. Don't edit.
include(./open62541_config.cmake file RESULT_VARIABLE build_config_found_path)
if (build_config_found_path STREQUAL NOTFOUND)
  message(FATAL_ERROR "Build config was not found -- invalid path or the file is not accessible. Use set_build_config to specify existing build config file. Build will terminate.")
endif()
